---
language: python
codecov: true
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
cache: pip
sudo: false
before_install:
  - pip install pipenv --upgrade
install:
  - rm -f Pipfile.lock
  - pipenv lock
  - pipenv sync --dev
script: pipenv run green -r -vvv
branches:
  only:
    - master
jobs:
  include:
    - stage: preflight
      python: '3.6'
      install:
        - pipenv sync --dev
      script:
        # - pipenv check
        - yamllint . -s
        - pylama -v .
stages:
  - preflight
  - test
after_success:
  - codecov
