[tool.poetry]
name = "cert_manager"
version = "2.4.0"
description = "Python interface to the Sectigo Certificate Manager REST API"
license = "BSD-3-Clause"
authors = ["Andrew Teixeira <teixeira@broadinstitute.org>"]
readme = "README.md"
repository = "https://github.com/broadinstitute/python-cert_manager.git"
homepage = "https://github.com/broadinstitute/python-cert_manager.git"
keywords = ["sectigo", "comodo", "certificate"]

[tool.poetry.dependencies]
python = "^3.7"  # Compatible python versions must be declared here
requests = "*"
toml = ">=0.9,<0.11"

[tool.poetry.dev-dependencies]
bump2version = "*"
coverage = ">=4.4.2"
fixtures = "*"
green = ">=2.12.0"
mock = ">=2.0.0"
pydocstyle = "<7"
pylint = "*"
pyyaml = "==6.0.1"
responses = "*"
testtools = "*"
twine = "*"
wheel = "*"
yamllint = "*"

[tool.ruff]
fixable = ["ALL"]
line-length = 120
select = [
  "D",   # pydocstyle
  "E",   # pycodestyle
  "F",   # pyflakes
  "I",   # isort
  "N",   # pep8-naming
  "PL",  # Pylint
  "UP",  # pyupgrade
]

[tool.ruff.pydocstyle]
convention = "google"
