---
version: 2.1

orbs:
  python: 'broadinstitute/bits-python@0.2.0'

workflows:
  preflight:
    jobs:
      - python/preflight:
          name: 'preflight-checks'
  test_and_deploy:
    jobs:
      - python/run-tests:
          name: 'python-2.7'
          version: '2.7'
      - python/run-tests:
          name: 'python-3.5'
          version: '3.5'
      - python/run-tests:
          name: 'python-3.6'
          version: '3.6'
      - python/run-tests:
          name: 'python-3.7'
          version: '3.7'
      - python/deploy:
          name: 'pypi-deploy'
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
