---
version: 2
workflows:
  version: 2
  preflight:
    jobs:
      - preflight
  test:
    jobs:
      - test36
      - test35
      - test34
      - test27
jobs:
  preflight:
    docker:
      - image: circleci/python:3.6-stretch
    working_directory: ~/repo
    environment:
      PIPENV_COLORBLIND: 1
      PIPENV_HIDE_EMOJIS: 1
      PIPENV_NOSPIN: 1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install pipenv
            rm -f Pipfile.lock
            pipenv lock
            pipenv sync --dev
      - run:
          name: Run linting
          command: |
            pipenv run yamllint . -s
            pipenv run pylama -v --skip '.venv/*'
  test36: &test-template
    docker:
      - image: circleci/python:3.6-stretch
    working_directory: ~/repo
    environment:
      PIPENV_COLORBLIND: 1
      PIPENV_HIDE_EMOJIS: 1
      PIPENV_NOSPIN: 1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install pipenv
            rm -f Pipfile.lock
            pipenv lock
            pipenv sync --dev
      - run:
          name: Run tests
          command: |
            pipenv run green -r -vvv
      - run:
          name: Upload coverage report
          command: |
            if [[ "$UPLOAD_COVERAGE" != 0 ]]; then
                pipenv run coverage xml
                pipenv run codecov --required -X search gcov pycov -f coverage.xml --flags $CIRCLE_JOB
            fi
  test34:
    <<: *test-template
    docker:
      - image: circleci/python:3.4-stretch
        environment:
          - UPLOAD_COVERAGE=0
  test35:
    <<: *test-template
    docker:
      - image: circleci/python:3.5-stretch
        environment:
          - UPLOAD_COVERAGE=0
  test27:
    <<: *test-template
    docker:
      - image: circleci/python:2.7-stretch
        environment:
          - UPLOAD_COVERAGE=0
