---
name: 'deploy'
permissions:
  contents: read
  pull-requests: read
'on':
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  pypi_deploy:
    uses: broadinstitute/shared-workflows/.github/workflows/python-deploy-to-pypi.yaml@v5.0.1
    secrets:
      pypi_token: ${{ secrets.PYPI_TOKEN }}
