---
name: 'deploy'

'on':
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  pypi_deploy:
    uses: broadinstitute/shared-workflows/.github/workflows/python-deploy-to-pypi.yaml@v3.2.0
    secrets:
      pypi_token: ${{ secrets.PYPI_TOKEN }}
